image: registry.gitlab.com/tplatzke/gitpod-docker/workspace:latest
ports:
- port: 9999
  onOpen: ignore
- port: 8001
  onOpen: notify
- port: 3306
  onOpen: ignore
- port: 6942
  onOpen: ignore
  
tasks:
  #- name: mysql
  #  command: connect-db
  #- name: apache
  #  command: APACHE_DOCROOT_IN_REPO=source apachectl start
  - name: composer install
    init: composer install --no-dev --no-plugins --no-scripts
    command: composer install --no-dev
vscode:
  extensions:
    - eamodio.gitlens
    - cweijan.vscode-mysql-client2
    - felixfbecker.php-debug
    - bmewburn.vscode-intelephense-client
